dataset:
  # iid or power-law
  split: 'iid'

model:
  _target_: tamuna.models.Net
  num_classes: 10

strategy:
  _target_: tamuna.strategy.TamunaStrategy

server:
  clients_per_round: 10
  num_clients: 1000
  num_rounds: 50
  # sparsity parameter, 2 <= s <= clients_per_round
  s: 8
  # probability of server communication, i.e. clients will in expectation do 1 / p local epochs
  p: 0.333
  server_device: 'cuda'

client:
  client_device: 'cuda'
  client_resources:
    num_cpus: 4
    num_gpus: 1
  learning_rate: 0.003
  # eta should be between p / 2 and p * [(clients_per_round * (s - 1))/(s * (clients_per_round - 1))]
  eta: 0.323
