#---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

#dataset:
#  # dataset config
#
#model:
#  # model config
#
#strategy:
#  _target_: # points to your strategy (either custom or exiting in Flower)
#  # rest of strategy config
#
#client:
#  # client config
---

model:
  _target_: tamuna.models.Net
  num_classes: 10

strategy:
  _target_: tamuna.strategy.TamunaStrategy

server:
  clients_per_round: 2
  num_clients: 5
  num_rounds: 5
  s: 2
  p: 0.333
  server_device: 'cuda'

client:
  client_device: 'cpu'
  client_resources:
    num_cpus: 2
    num_gpus: 0
  learning_rate: 0.02
  eta: 0.333
